apiVersion: v1
kind: Pod
metadata:
  name: uvprint-greeting
spec:
  containers:
    - name: env-print-uvdemo
      image: bash
      env:
        - name: GREETING
          value: "Warm greetings to"
        - name: HONORIFIC
          value: "The most honorable"
        - name: NAME
          value: "Kubernetes"
      command: ["echo"]
      args: ["$(GREETING) $(HONORIFIC) $(NAME)"]
