apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deploymentwithtaint
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
      - key: "taintdemo"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: nginx-container
        image: nginx:1.7.9
        ports:
        - containerPort: 80
 
