apiVersion: v1
kind: Service
metadata:
  name: my-np-service
spec:
  type: NodePort
  selector:
    app: metrices
    department: engineering
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50000

